#!/bin/bash

arangosh --server.password root --javascript.execute-string "db._createDatabase('ldbc_snb_sf0001'); db._useDatabase('ldbc_snb_sf0001'); db._create('Forum'); db._create('Message'); db._create('Organisation'); db._create('Person'); db._create('Place'); db._create('Tag'); db._create('TagClass'); db._createEdgeCollection('containerOf'); db._createEdgeCollection('hasCreator'); db._createEdgeCollection('hasInterest'); db._createEdgeCollection('hasMember'); db._createEdgeCollection('hasModerator'); db._createEdgeCollection('hasTag'); db._createEdgeCollection('hasType'); db._createEdgeCollection('isLocatedIn'); db._createEdgeCollection('isPartOf'); db._createEdgeCollection('isSubclassOf'); db._createEdgeCollection('knows'); db._createEdgeCollection('likes'); db._createEdgeCollection('replyOf'); db._createEdgeCollection('studyAt'); db._createEdgeCollection('workAt');"

for file in $(ls comment_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Message --translate "id=_key"; done
for file in $(ls forum_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Forum --translate "id=_key"; done
for file in $(ls organization_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Organization --translate "id=_key"; done
for file in $(ls person_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Person --translate "id=_key"; done
for file in $(ls place_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Place --translate "id=_key"; done
for file in $(ls post_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Message --translate "id=_key"; done
for file in $(ls tag_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection Tag --translate "id=_key"; done
for file in $(ls tagclass_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --type csv  --separator "|" --collection TagClass --translate "id=_key"; done

for file in $(ls comment_hasCreator_person_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection hasCreator --to-collection-prefix Person --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls comment_hasTag_tag_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection hasTag --to-collection-prefix Tag --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls comment_isLocatedIn_place_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection isLocatedIn --to-collection-prefix Place --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls comment_replyOf_comment_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection replyOf --to-collection-prefix Message --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls comment_replyOf_post_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection replyOf --to-collection-prefix Message --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls forum_containerOf_post_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Forum --collection containerOf --to-collection-prefix Message --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls forum_hasMember_person_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Forum --collection hasMember --to-collection-prefix Person --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls forum_hasModerator_person_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Forum --collection hasModerator --to-collection-prefix Person --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls forum_hasTag_tag_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Forum --collection hasTag --to-collection-prefix Tag --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls organisation_isLocatedIn_place_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Organisation --collection isLocatedIn --to-collection-prefix Place --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_hasInterest_tag_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection hasInterest --to-collection-prefix Tag --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_isLocatedIn_place_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection isLocatedIn --to-collection-prefix Place --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_knows_person_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection knows --to-collection-prefix Person --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_likes_comment_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection likes --to-collection-prefix Message --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_likes_post_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection likes --to-collection-prefix Message --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_studyAt_organisation_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection studyAt --to-collection-prefix Organisation --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls person_workAt_organisation_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Person --collection workAt --to-collection-prefix Organisation --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls place_isPartOf_place_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Place --collection isPartOf --to-collection-prefix Place --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls post_hasCreator_person_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection hasCreator --to-collection-prefix Person --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls post_hasTag_tag_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection hasTag --to-collection-prefix Tag --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls post_isLocatedIn_place_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Message --collection isLocatedIn --to-collection-prefix Place --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls tagclass_isSubclassOf_tagclass_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Tagclass --collection isSubclassOf --to-collection-prefix Tagclass --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
for file in $(ls tag_hasType_tagclass_[0-9]*_0.csv); do arangoimport --server.password root --server.database ldbc_snb_sf0001 --file ${file} --from-collection-prefix Tag --collection hasType --to-collection-prefix Tagclass --type csv --separator "|" --translate "src.id=_from" --translate "dst.id=_to"; done
